<?php die("Access Denied"); ?>#x#a:2:{s:6:"result";a:5:{i:0;O:8:"stdClass":3:{s:4:"link";s:44:"https://virtuemart.net/news/506-virtuemart-4";s:5:"title";s:12:"VirtueMart 4";s:11:"description";s:8194:"<p style="text-align: justify;">We are pleased to release a new VirtueMart generation, which adds compatibility with Joomla 4 and PHP8. VirtueMart 4 comes with a new overridable Bootstrap 3 frontend template (Bootstrap 5 will follow soon) and new backend template. Of course there are also new features for the product presentation, a lot of bugfixes and some new programming techniques. We originally had planned to release this on Christmas, but it was not possible to keep the date due to many changes applied to joomla 4 after it's initial release. We still have to iron out a few minor complications with it, but it already works for a number of early adopters..</p>
<p><img src="https://virtuemart.net/images/vm4_newshead6_blur_small.jpg" alt="" width="690" /></p>
<h4 style="text-align: justify;">The Backend Template</h4>
<p style="text-align: justify;">The new backend template uses VMUI-Kit. Unluckily this is not ideal for Joomla 4, but BS5 will be added soon. You can choose between four different color styles and it works well on mobiles. Updaters must install it manually, because it is handled as an installable template and is not part of the VirtueMart core installation package.</p>
<h4 style="text-align: justify;">New backend features and tools</h4>
<p style="text-align: justify;">VirtueMart 4 not only has a new look, but also new functions in the backend. For example, Multivariants with children can now be autogenerated with permutating variants. Customfields can have their own SKU, GTIN, MPN. The order status was previously limited to a single character and is now extended to 3 chars. The category dropdown in the "product.edit" view now also lists unpublished categories. Original language flags (as we have already for other edits) now added to the payment and shipment edit views. RuposTel donated a google like search for products and orders. So for example use sku:mySkuToSearch to let VM search only within the SKUs.</p>
<p style="text-align: justify;">Also there are two new maintenance tools. The first one is a synchronizer consisting of three buttons, which sets country 2, country 3 and country numerical code in the country list correctly according to ISO 3166. The second one is a converter button for changing old utf8mb3 tables to utf8mb4 tables.</p>
<h4 style="text-align: justify;">New frontend template</h4>
<p style="text-align: justify;">Spyros Petrakis has generously donated his Horme3 template for the VirtueMart Core. Another new feature which you will find most useful is the the setting for different Bootstrap layouts, which was not fully implemented yet and therefore useless, ...until now! Selecting the Bootstrap 3 layouts in the configuration will load these layouts from the core. So we can now use any Bootstrap 3 template without overrides, because VirtueMart 4 loads the Horme3 ones. This also gives new users the possibility to use old override techniques. We are planning to extend this technique to modules and css. Work is already in progress to provide the same technique for Bootstrap 5.</p>
<p style="text-align: justify;">The javascript also received a general overhaul, so it is more reliable, should work better on different browsers and is easier to handle for templaters (working relative or with classes instead of ids). The new fancybox 1.3.4.2 is working with the new jQuery version now.</p>
<h4 style="text-align: justify;">Paybox</h4>
<p style="text-align: justify;">The payment plugin Paybox got a general overhaul and works now with 3Dsecure V2</p>
<h4 style="text-align: justify;">Product Bundles</h4>
<p style="text-align: justify;">are a very mighty new feature. It can be used as typical bundle of different products for one price. This was also possible before by just creating a product which listed the included products. But this method required a lot maintenance. The inventory just listed a sold bundle, but did not update the inventory per product. If you sold a bundled product also as a bulk-version, then the system used two different products. If you updated the price of the bulk version, nothing changed on the bundles version. Not any longer! The new product bundles make real bundles of different existing VirtueMart products. They can be included for free or also as variants with an extra price. The prices can be a fixed amount or a percentage. So it can also be used for cross-selling and discounts.</p>
<h4 style="text-align: justify;">Extra related product groups</h4>
<p style="text-align: justify;">are also used for cross-selling or presentation of complementary items. They are basically the same as the default related products, but can have another title and appear somewhere on product details page.</p>
<h4 style="text-align: justify;">Better search with tags</h4>
<p style="text-align: justify;">Enhanced search using the customfield searchable tag system. Searching for more than 1 tag now displays only products fitting to any requested tag..</p>
<h4 style="text-align: justify;">Keep cart content for guests</h4>
<p style="text-align: justify;">Added storing of carts for unregistered users as a cookie. This works only for SSL secured pages.</p>
<h4 style="text-align: justify;">and more</h4>
<ul>
<li style="text-align: justify;">really a lot work on caches (internal, external), table indexes and other optimisations.</li>
<li style="text-align: justify;">additionally general work to please the JED Checker.</li>
<li style="text-align: justify;">option to display thumbnails to select children of multivariants.</li>
<li style="text-align: justify;">different email layouts by order status to enhance the customer communication.</li>
<li style="text-align: justify;">you can create a category menu item which clears the cart by category.</li>
</ul>
<h3>Changes for developers</h3>
<p>ATTENTION: Triggers are case sensitive in joomla 4! <br />Changed triggers:</p>
<ul>
<li>plgVmOnStoreProduct($data, $plugin_param) changed to function plgVmOnStoreProduct($data, $plugin_param, $key)</li>
<li>plgVmonSelectedCalculatePrice to plgVmOnSelectedCalculatePrice (lower to upper case)</li>
<li>in calculation plgVmOnDisplayEdit to plgVmOnDisplayEditCalc</li>
</ul>
<p>new triggers</p>
<ul>
<li>product and order model, added new trigger plgVmMySortSearchListProductsQuery respectivly plgVmMySortSearchListOrdersQuery in exeSortSearchListQuery which is at begin and can takeover the whole function (for searchplugins)</li>
</ul>
<p>Plugin Handler</p>
<ul>
<li>Added vdispatcher.php as proxy for the joomla dispatcher</li>
<li>We can use now $results = vDispatcher::trigger('event', array(param1, param2,...));</li>
<li>the directTrigger can now execute a certain event of a plugin family, too.</li>
<li>added function reloadPlugins, which loads again the payment/shipment methods of the plugins. The cart unloads them, if they do not fit, 3rd party developer can reload them, that way.</li>
</ul>
<p>Technics</p>
<ul>
<li>setConvertDecimal for plugins, tables</li>
<li>set datefields for tables</li>
<li>$this-&gt;_genericVendorId = false prevents that the tables sets the virtuemart_vendor_id generically</li>
<li>added extra parameter to vmuploader so that it works also with other input names</li>
<li>the product model sortSearchListQuery is now working with an extra parameter, which can override an "Request" variables. So using old vRequests parameters is just used as fallback now.</li>
<li>function getProductListing is now using request params only for the group "products", not for the other groups like featured, recent, topten, and so on</li>
<li>vmecho again a bit enhanced, if debug is activated vmInfo are quequed as vmdebug (so the messages appear in the real order)</li>
<li>field products, added a category filter</li>
<li>changed ajax js for dynamic page reload, a ready script in the layout is not needed anylonger</li>
<li>added cart functions getCartWeight and getCartQuantity</li>
<li>removed the problem that a delivery note created an invoiceNumber</li>
<li>Time of the calculationHelper considers offset</li>
</ul>
<p style="text-align: center;"><a class="button-primary" href="https://virtuemart.net/download">DOWNLOAD VirtueMart 4 <br /> NOW</a></p>";}i:1;O:8:"stdClass":3:{s:4:"link";s:57:"https://virtuemart.net/news/505-virtuemart-4-for-joomla-4";s:5:"title";s:25:"VirtueMart 4 for Joomla 4";s:11:"description";s:2368:"<p style="text-align: justify;">We know you are all expecting VirtueMart 4 for Joomla 4 to be released soon. We are almost there. Our new version is being tested daily in various test environments and most features are working to our satisfaction. So well, in fact, that the first VM testers are planning to go live with smaller stores soon.</p>
<h2 style="text-align: justify;">VirtueMart 4 Update Procedure</h2>
<p style="text-align: justify;">Upgrade or Migration? Don't worry, the changes in Joomla 4 are substantial in some areas, but we have made sure that you can update from VirtueMart 3 to VirtueMart 4 like a normal update, mostly with just a click of a button. We can provide you with an installation package that is compatible with Joomla 3 and Joomla 4.</p>
<h2 style="text-align: justify;">VirtueMart 4 loves Testers</h2>
<nav>
<p style="text-align: justify;">Due to the extensive changes we still have some work remaining and would be happy if you test our current RC versions for Joomla 3 and Joomla 4, which you can find at <a class="btn" href="https://dev.virtuemart.net/projects/virtuemart/files">dev.virtuemart.net</a></p>
</nav>
<p style="text-align: justify;"><img src="https://virtuemart.net/images/Panorama-Lilienstein-von-Waitsdorf.jpg" alt="Panorama Lilienstein von Waitsdorf" /></p>
<p style="text-align: justify;"><small>Saxonian Swizz Lilienstein, Copyright Max Milbers</small></p>
<h2 style="text-align: justify;">Next Release</h2>
<p style="text-align: justify;">We will soon provide a new version, even if it is not yet fully perfected for Joomla 4, as we have also made many enhancements for existing VirtueMart stores with Joomla 3.</p>
<h2 style="text-align: justify;">When to Update?</h2>
<p style="text-align: justify;">Joomla 3.10 is officially supported until August 17, 2023. So there is no need to rush to update to Joomla 4 immediately. Joomla 4 is still a new software, so we recommend to wait a bit with live store updates until the community has fully tested Joomla 4. New software always tends to have some bugs that need to be discovered and ironed out in the beginning.</p>
<p style="text-align: justify;">Help Joomla 4 and VirtueMart 4 by testing in your test environments.</p>
<p style="text-align: justify;">We expect that late spring 2022 will be a good time to update the first live stores without any problems.</p>";}i:2;O:8:"stdClass":3:{s:4:"link";s:104:"https://virtuemart.net/news/503-release-virtuemart-3-8-8-updated-administrator-interface-template-design";s:5:"title";s:74:"Release VirtueMart 3.8.8 - Updated administrator interface template design";s:11:"description";s:7583:"<p>Here are some words by the leader of VirtueMart (Max Milbers): <em>These are ambivalent times. On one hand life changed completly for most members, on the other hand it offers new opportunities. In my case, I am currently very busy with the lockdown problems. Literally getting a simple screw is suddenly a big time consuming problem. Politics divide people and business. I got indirect questions, asking if VirtueMart is going to take measures concerning it's 'political correct use'. When I joined <em>VirtueMart</em>, my goal was to create a free shop system for the people. VirtueMart is a free Open source system for anyone. No community member can controll, what you sell with it. It is not our responsibility. Personally I believe in the good will of people and that no one should judge about others without walking in their shoes for a while. We, the VirtueMart communtiy, have members all over the world.&nbsp;Let's keep it that way! </em></p>
<p>Now back to VirtueMart. We tried already a year ago to create a new admin template. This time our team member Valerie Isaksen of alatak.net broke through the obstacles and lightend a new fire for the new administrator template. The old template will be later merged into the new template and provided as style, or theme (it won't be exactly the same). The new admin template is currently provided as backend template. Updaters should use our <strong>package</strong>&nbsp;(use the big blue download button) to get the new admin template. You can just install the package over your current installation. It ensures that you get also the latest tcpdf and vmbeez. But you can also extract it and install the vmadmin.zip. This way ensures that the changes in the backend template do not interfere any productive installation.</p>
<h2>Updated administrator interface template design</h2>
<p>A new administrator template is available for testing which improves mobile and desktop appearance and usability for shop administrators.</p>
<p>Modern icons are used to represent key features and give the interface a cleaner appearance.</p>
<p>Feedback tells us that the rich core features and configuration flexibility remain a core aspect of why VirtueMart is a great choice for Joomla ecommerce.</p>
<p>This is therefore a template UI update and not a complete redesign of administration pages. Shop owners will still find their business information and configurations in the same place.</p>
<p>A small number of configuration screens have had their look slightly modified using icons and give a more consistent alignment of features/fieldnames with input/selection.</p>
<p><img class="size-auto align-left" style="margin-bottom: 20px; display: block; margin-left: auto; margin-right: auto;" src="https://virtuemart.net//images/stories/orders.png" alt="" /></p>
<p style="text-align: center;"><a class="button-primary" href="https://virtuemart.net/download">DOWNLOAD VM3 NOW<br /> VirtueMart 3 component (core and AIO)</a></p>
<h2>Highlights</h2>
<ul class="check">
<li>Sidebar
<ul>
<li>Cleaner look and feel toggle functionality.</li>
<li>Is hidden completely and available via slide or overlay toggle in all views - giving more space for information to be displayed</li>
</ul>
</li>
<li>Mobile/Tablet:
<ul>
<li>List displays for the majority of VM administration functions now wrap effectively.</li>
<li>Function selections (filter/search) are shown correctly.</li>
<li>Alignment of fieldname with selection/input facilitates easier desktop viewing and significantly improves UI on Mobile/Tablets.</li>
</ul>
</li>
<li>General
<ul>
<li>General improved use of icons.</li>
<li>Cleaner tab selections for multipage configurations.</li>
<li>Simple radio yes/no selectors now align with Joomla UI look and feel.</li>
<li>Image view and upload - small design change improvement for Products/Categories/Manufacturers and Media.</li>
</ul>
</li>
</ul>
<p><img class="size-auto align-left" style="display: block; margin-left: auto; margin-right: auto;" src="https://virtuemart.net//images/stories/order.png" alt="" /></p>
<p style="text-align: center;"><a class="button-primary" href="https://virtuemart.net/download">DOWNLOAD VM3 NOW<br /> VirtueMart 3 component (core and AIO)</a></p>
<h2>New features, enhancements, fixes</h2>
<h3>Enhanced or new</h3>
<ul>
<li>Skrill payment update</li>
<li>Removed shop is offline feature. Added instead a link showing better possibilities todo that (Using joomla or catalog mode).</li>
<li>Restriction for shipment/payment byCoupon</li>
<li>Extra order note. Just a simple note for orders for internal use.</li>
<li>Order list searches now also for the customer_note and order_note</li>
<li>Order list now also filterable by vendor</li>
<li>New options of storing carts (currently per hidden configuration)<ol>
<li>#CartsDontSave = 0 //dont store carts for logged in shoppers</li>
<li>#CartsDontSaveByshoppergroup=50 //dont store carts for shoppers in this shoppergroup</li>
<li>#CartsDontSaveCartFields=1 //dont store cart fields when storing a cart for a shopper</li>
</ol></li>
<li>Order model function getOrder loads now the whole data of an order status (interesting for templaters)</li>
<li>Multiple category filter for product list in the backend. Disabled by default, currently you can enable it by hidden config AllowMultipleCatsFilter=1</li>
</ul>
<h3>New for developer</h3>
<ul>
<li>new pattern if an array is given, and we need the first item then we use now reset and not the 0 item.</li>
<li>New Trigger in storeProductCustomfields, for removed customfields.</li>
<li>Added "andWhere" function to parameter to VmTableXarray load function, added function loadOrderingCurrentItem</li>
<li>VmTable cleaned ordering, added function loadOrderingCurrentItem</li>
<li>PHP 8 compatibility, bugs may still occur.</li>
</ul>
<h3>Fixes</h3>
<ul>
<li>Ordering for products</li>
<li>All nasty warnings like "Warning: Parameter 1 to plgVmShipmentWeight_countries::plgVmOnSelectCheckShipment() expected to be a reference, value given in /var/www/vhosts/..../libraries/joomla/event/event.php on line 70"</li>
<li>time for coupons is from now on not "NOW" but "timestamp_utc"</li>
<li>Fix for 1054 Unknown column 'Array' in 'where clause after update to 3.8.6 http://forum.virtuemart.net/index.php?topic=145855.30 Fix for ordering of products if products of subcategories shown</li>
<li>The order detail links in the email consider the case, that neither guest link, nor registered is set</li>
<li>Feature that registered users must activate themself</li>
<li>getUserInfoInUserFields getting the right joomla user data per given id</li>
<li>Missing cart error message in js</li>
<li>Missing '' for constant VMPATH_ROOT in installer script</li>
<li>Removed useless \n in Sample shop decription</li>
<li>getVendorAddressFields when a administrator and vendor edits another vendor.</li>
<li>category model calls to clearCategoryRelatedCaches</li>
<li>language of shipment plugin in order view</li>
<li>added chosenDropDowns in cart default shopperform</li>
<li>little fix for custom cartlayout</li>
<li>Copyright years updated, renamed variables and other minors</li>
<li>fixed a lot warnings of the type "Deprecated: Required parameter $isSite follows optional parameter $selectedCategories in /var/www/vhosts/.../administrator/components/com_virtuemart/helpers/shopfunctions.php on line 652". So we are already prepared for PHP8.</li>
</ul>
<p style="text-align: center;"><a class="button-primary" href="https://virtuemart.net/download">DOWNLOAD VM3 NOW<br /> VirtueMart 3 component (core and AIO)</a></p>";}i:3;O:8:"stdClass":3:{s:4:"link";s:94:"https://virtuemart.net/news/502-security-release-virtuemart-3-8-6-closing-an-xss-vulnerability";s:5:"title";s:62:"Security Release VirtueMart 3.8.6 Closing an XSS Vulnerability";s:11:"description";s:5650:"<p>A new XSS was found by 4N_CURZE (https://www.openbugbounty.org/researchers/4N_CURZE/). It took a while to reproduce it, because it was caused by the manufactuer dropdown, which is not always activated. The problem itself was easy to fix, although the value was whitelisted everywhere else, it was missing for the manufacturer drop-down list.</p>
<p>Since the previous release some features got added. The long desired multicart system got implemented. Multicart means for a multi-vendor shop, that there is an extra cart for each vendor. So when a customer buys products from different vendors he needs to do a checkout for every vendor. This system is very interesting for real marketplaces, which offer products of different vendors.</p>
<p>Another nice new feature are payment/shipment restrictions by coupons. This can be used to offer customers other payment methods over the phone, such as bank transfer for example. Or it can be used for marketing campaigns like "use this coupon to get free shipment".</p>
<p>The textinput plugin can now be used for mandatory text, as we have introduced a required characters check.&nbsp;iStraxx contributed the toggleCartButton.js with MIT license for the required characters check.</p>
<p>StAn of RuposTel has provided a useful overhaul of the VirtueMart recaptcha system. It now works according to the new Joomla standards and works with any joomla captcha plugin. Read more about this on <a href="http://docs.virtuemart.net/tutorials/administration-configuration-vm-2/243-new-captcha-system-in-virtuemart-3-8-6.html">docs.virtuemart.net</a></p>
<p style="text-align: center;"><a class="button-primary" href="https://virtuemart.net/download">DOWNLOAD VM3 NOW<br /> VirtueMart 3 component (core and AIO)</a></p>
<p>&nbsp;</p>
<p>Multivendor:</p>
<ul>
<li>Added MultiCart system</li>
<li>Cart module, replaced link to cart against button, old links should still work</li>
<li>Vendor dropdown for Categories.</li>
<li>Added the feature that subvendors can check orders, but only if at least one product of them is on the order.</li>
</ul>
<p>&nbsp;</p>
<p>Extended features</p>
<ul>
<li>Added shipment/payment restriction by Coupon</li>
<li>Added required chars to the textinput plugin</li>
<li>Added layout orderdone for weight_countries plugin, which can be used to override the standard output</li>
<li>Added a warning to the vmconfig if the price config is overwritten by shoppergroups.</li>
<li>Product edit view and model, added filter for published/unpublished, added searching of products in multiple categories</li>
</ul>
<p>&nbsp;</p>
<p>Language:</p>
<ul>
<li>Added&nbsp;VM config setting ReInjectJLanguage, which replaces the Joomla JLanguage object with VmLanguage</li>
<li>Update for the VirtueMart System Plugin, for multilanguage as it may be useful to load the&nbsp;VM config always first</li>
<li>Replaced $languages = JLanguageHelper::createLanguageList against $JLanguages = JHtml::_('contentlanguage.existing')</li>
</ul>
<p>&nbsp;</p>
<p>Security:</p>
<ul>
<li>XSS leak fixed in manufacturer dropdown</li>
<li>Recaptcha Overhaul by StAn of RuposTel</li>
</ul>
<p>&nbsp;</p>
<p>Payments:</p>
<ul>
<li>PayPal refund configuration option to prevent VM generating a request for PayPal refund</li>
<li>Small paypal enhancement, inspired by RuposTel and written by Quorvia</li>
</ul>
<p>&nbsp;</p>
<p>Development:</p>
<ul>
<li>category model added function getChildCategoryListObjectByCachedOption which is now used by getChildCategoryList and getChildCategoryListObjectByCachedOption&nbsp;&nbsp;</li>
<li>function getSafePathFor can now be used to create any kind of subfolder</li>
<li>custom model, directTrigger for plgVmDeclarePluginParamsCustomVM3 and plgVmGetTablePluginParams vmplugin.php enhanced function declarePluginParams</li>
<li>Fixed customfield model cache. We load now always all attributes and cache that. and we use directTrigger for plgVmDeclarePluginParamsCustomVM3</li>
<li>user model, added cache</li>
<li>user model, set the function "setId" to deprecated. The use of the internal id as pointer is useless. The function getUser should now be called with id, but usese as fallback the old $this-&gt;_id construction</li>
<li>userfield model added JPluginHelper::importPlugin('user'); to the getUserFieldsFor function</li>
<li>iStraxx added the toggleCartButton.js with MIT license, need for the textinput required letters.&nbsp;</li>
<li>Invoice, the product is always reloaded to create the item.&nbsp;</li>
</ul>
<p>&nbsp;</p>
<p>Fixes:</p>
<ul>
<li>Small fix for coupons using the correct language</li>
<li>Fixed that Calculation rules were not including the given end day, because the hours and seconds were not set</li>
<li>added registration of Vm Controller and View to massxref.php</li>
<li>vmTable warning if a key of the params is accidently empty</li>
<li>Added _genericVendorId to vmtable and fallback&nbsp;</li>
<li>tables/order_items.php added the very important $this-&gt;_genericVendorId = false to fix virtuemart_vendor_id of order items.</li>
<li>Updates for the joomla fullinstaller</li>
<li>little fix for updatesmigration in case of multivendor store</li>
<li>little fix for the tableupdater to prevent notice.</li>
<li>important fix for the backend user view to ensure that the correct addresses are loaded.</li>
<li>fixes for tcpdf to work on higher php versions</li>
<li>fixed function updateCategory for the xref data</li>
<li>fixed tooltip in config (check for existing lang key did not work the old way anylonger)</li>
<li>mail_raw_pricelist.php replaced $item-&gt;product_final_price against $item-&gt;product_subtotal_with_tax</li>
</ul>";}i:4;O:8:"stdClass":3:{s:4:"link";s:76:"https://virtuemart.net/news/501-skrill-merchant-on-boarding-virtuemart-3-8-4";s:5:"title";s:45:"Skrill Merchant On Boarding, VirtueMart 3.8.4";s:11:"description";s:4331:"<h3>Great update of the Skrill Plugin</h3>
<p>Trusted by millions across the globe Skrill meets the needs of more than 156,000 businesses worldwide providing a convenient and secure way to send and receive money in nearly 200 countries and 40 currencies.</p>
<p>Our payments platform comes with an exclusive reduced fee offer of 0.9% on Debit Card/Prepaid Card/Credit Card (VISA, Mastercard, Maestro) transactions, and 0.5% fees on Rapid Transfer transactions.*<br /> *Fees apply to new merchants only within restricted industry sectors.&nbsp;<a href="https://www.skrill.com/en/footer/terms-conditions/fees-reduction-promotion/">Terms and conditions apply.</a></p>
<p><a href="https://www.skrill.com/en/business/ecommerce-promotion/?utm_source=virtue-mart&amp;utm_medium=banner&amp;utm_campaign=ecomprom&amp;utm_content=product-page&amp;rid=128963654"><img style="float: right;" src="https://virtuemart.net/images/stories/news/CCRT_ShoppingCartPartners_900x516_EN_CTA.jpg" alt="CCRT ShoppingCartPartners 900x516 EN CTA" width="321" height="184" /></a></p>
<p>What this module does for you:</p>
<ul>
<li>Free and quick setup</li>
<li>Access credit cards and 100+ local payment solutions with 1 easy integration</li>
<li>Take advantage of the Skrill multicurrency account, giving you access to 40+ currencies</li>
<li>High-security standards and anti-fraud technology</li>
<li>Seamless payment experience across mobile, tablet and desktop</li>
<li>Connect with millions of Skrill account holders</li>
</ul>
<p>Features:</p>
<ul>
<li>Additional payment options and control over how they are displayed</li>
<li>Customizable gateway with embedded page and redirect functionality</li>
<li>Instant settlement</li>
<li>Enhanced reporting and transaction status viewing</li>
<li>Refund capability within VirtueMart</li>
</ul>
<p>What your customers will like:</p>
<ul>
<li>Easy ways to pay safely online – no sign-up required to make payments</li>
<li>Convenient and immediate payments – pay with a bank account, or debit and credit cards without any hassle</li>
<li>Multiple local payment options allowing customers to pay how they want</li>
<li>Internationally recognized and trusted brand</li>
</ul>
<p>Don’t have an account?&nbsp;<a href="https://signup.skrill.com/onboarding/#/?rdu=onboarding&amp;rid=128963654">Sign up for free today!</a></p>
<p>&nbsp;</p>
<p style="text-align: center;"><a class="button-primary" href="https://virtuemart.net/download">DOWNLOAD VM3 NOW<br /> VirtueMart 3 component (core and AIO)</a></p>
<h4>VirtueMart, List of Bugfixes:</h4>
<ul>
<ul>
<li>PayPal Smartbuttons should not redirect in checkout if called without redirect option</li>
<li>removed useless mod_virtuemart_product_helper and other minors</li>
<li>enhanced displayIt function, it resolves now all parameters to an array and only the non empty ones are written. It is also possible now to remove the parameter src completly or replace it with another name. For example when the array has 'src' =&gt; 'data-src', then the parameter src is renamed to data-src and filled with the correct URL.</li>
<li>enhanced lazyLoad configuration, added GUI option in template tab of vm config</li>
<li>css addtocart, addtocart-disabled and notify, All buttons should have the same height.</li>
<li>New language variables for new reviews feature.New language variables for new reviews feature.</li>
<li>Mediahandler adjustment php7.4</li>
<li>order updateBill sql a plus was not commented</li>
<li>country table added UNIQUE to the indexes of country 2 and country 3 code.</li>
<li>added Paraguay states</li>
<li>removed old jquery.min we use now always the joomla one.</li>
<li>created GUI for hidden config pricesbyCurrency, extended it by one option (restrictiv)</li>
<li>Pagination for coupon analytics</li>
<li>fixed wrong invoice numbers generated if fired in the order edit view <a href="http://forum.virtuemart.net/index.php?topic=144911.0fixed">http://forum.virtuemart.net/index.php?topic=144911.0</a></li>
<li>translated address in cart (translated countries)</li>
<li>fixed router in case sef is disabled and an array is used in the url</li>
<li>it could happen that payment or shipment was not set due a conflicting js, the js is now unbound for these radios</li>
<li>renderMetaEdit added real option for "index, follow".</li>
</ul>
</ul>";}}s:6:"output";s:0:"";}